import Foundation

/// Generates a Claude Code **managed-settings.json** (enterprise policy file)
/// carrying Throttle's recommended hardening — for an admin to distribute to a
/// team via MDM. This is the LOCAL-CONFIG survivor of the B2B idea: Throttle
/// generates the policy; the admin distributes it. No cloud, no accounts, no
/// reporting — the USP stays intact.
///
/// Claude Code reads managed settings from a system path (e.g.
/// `/Library/Application Support/ClaudeCode/managed-settings.json` on macOS),
/// which only an admin can write — so it ENFORCES policy across a team.
enum TeamPolicyService {

    /// The recommended team policy JSON (pretty-printed, ready to deploy).
    static func generate() -> String {
        let policy: [String: Any] = [
            "$comment": "Generated by Throttle — Claude Code team hardening policy. Deploy to /Library/Application Support/ClaudeCode/managed-settings.json via MDM to enforce across the team.",
            "model": "claude-sonnet-4-6",
            "alwaysThinkingEnabled": false,
            "outputStyle": "Throttle Concise",
            "permissions": [
                "deny": [
                    "Read(./.env)", "Read(./.env.*)",
                    "Read(./node_modules/**)", "Read(./dist/**)", "Read(./build/**)",
                    "Bash(git push *)", "Bash(rm -rf *)",
                ],
            ],
        ]
        guard let data = try? JSONSerialization.data(
            withJSONObject: policy, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]),
              let s = String(data: data, encoding: .utf8) else { return "{}" }
        return s + "\n"
    }

    /// Where Claude Code reads enterprise managed settings (admin-only path).
    static let deployPath = "/Library/Application Support/ClaudeCode/managed-settings.json"
}
